/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import types.ICanvas;
import types.IGraph;
import types.ITool;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author dpf
 */
public class Graph extends javax.swing.JFrame implements IGraph {   
    
    private final ICanvas canvas;
    
    /**
     * Creates new form Graph
     * @param canvas
     */
    public Graph(Canvas canvas) {
        initComponents();
        this.canvas = canvas;
        canvasPanel.setLayout(new BoxLayout(canvasPanel,BoxLayout.Y_AXIS));
        utilityPanel.setLayout(new BoxLayout(utilityPanel,BoxLayout.Y_AXIS));
        toolsPanel.setLayout(new BoxLayout(toolsPanel,BoxLayout.Y_AXIS));
        canvasPanel.add(canvas);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsPanel = new javax.swing.JPanel();
        utilityPanel = new javax.swing.JPanel();
        canvasPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuEdit = new javax.swing.JMenu();
        edit_undo = new javax.swing.JMenuItem();
        edit_redo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout toolsPanelLayout = new javax.swing.GroupLayout(toolsPanel);
        toolsPanel.setLayout(toolsPanelLayout);
        toolsPanelLayout.setHorizontalGroup(
            toolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        toolsPanelLayout.setVerticalGroup(
            toolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        utilityPanel.setName(""); // NOI18N
        utilityPanel.setPreferredSize(new java.awt.Dimension(300, 0));

        javax.swing.GroupLayout utilityPanelLayout = new javax.swing.GroupLayout(utilityPanel);
        utilityPanel.setLayout(utilityPanelLayout);
        utilityPanelLayout.setHorizontalGroup(
            utilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        utilityPanelLayout.setVerticalGroup(
            utilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        menuFile.setText("File");
        menuBar.add(menuFile);

        menuEdit.setText("Edit");

        edit_undo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        edit_undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/undo.png"))); // NOI18N
        edit_undo.setText("Undo");
        edit_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_undoActionPerformed(evt);
            }
        });
        menuEdit.add(edit_undo);

        edit_redo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        edit_redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/redo.png"))); // NOI18N
        edit_redo.setText("Redo");
        edit_redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_redoActionPerformed(evt);
            }
        });
        menuEdit.add(edit_redo);

        menuBar.add(menuEdit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(utilityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(utilityPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(canvasPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_undoActionPerformed
        canvas.unDo();
    }//GEN-LAST:event_edit_undoActionPerformed

    private void edit_redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_redoActionPerformed
        canvas.reDo();
    }//GEN-LAST:event_edit_redoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JMenuItem edit_redo;
    private javax.swing.JMenuItem edit_undo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPanel toolsPanel;
    private javax.swing.JPanel utilityPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getToolsPanel() {
        return toolsPanel;
    }
    
    @Override
    public JPanel getUtiliyPanel() {
        return utilityPanel;
    }
    
    @Override
    public JPanel getCanvasPanel() {
        return canvasPanel;
    }

    @Override
    public ICanvas getCanvas() {
        return canvas;
    }

    @Override
    public void addToToolbar(ITool tool) {
        canvas.addTool(tool);
        tool.setCanvas(canvas);
        JButton b = new JButton();
        b.setMargin(new Insets(0, 0, 0, 0));
        b.setToolTipText(tool.getToolName());
        b.addActionListener((ActionEvent e) -> {
            canvas.openTool(tool, null);
        });
        b.setIcon(tool.getIcon());
        getToolsPanel().add(b);
    }

}
