/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.bezier;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import types.ICanvas;

/**
 *
 * @author dpf
 */
public class BezierUtilityPanel extends javax.swing.JPanel {
    
    private static final String DEGREE_LABEL_TEXT = "Current degree       ";
    
    private BezierCurves bc;
    private final Bezier b;
    
    /**
     * Creates new form BezierUtilityPanel
     * @param b
     * @param maxSize
     */
    public BezierUtilityPanel(Bezier b, int maxSize) {
        initComponents();
        this.b = b;
        colorChooser.setColor(ICanvas.DEFAULT_DRAW_COLOR);
        if(maxSize >1){
            sliderSize.setMinimum(1);
            sliderSize.setMaximum(maxSize);
            sliderSize.setValue(1);
        }
        colorChooser.getSelectionModel().addChangeListener((ChangeEvent e) -> {
            b.recompute();
        });
        
        degreeLabel.setText(DEGREE_LABEL_TEXT+0);
        sliderSplineLabel.setText("1");
        sliderSpline.setValue(100);
    }

    public void setBezierCurves(BezierCurves bc) {
        this.bc = bc;
    }
    
    public int getDrawSize(){
        return sliderSize.getValue();
    }
    
    public Color getColor(){
        return colorChooser.getColor();
    }
    
    public void setDrawSize(int drawSize){
        sliderSize.setValue(drawSize);
    }
    
    public void setColor(Color color){
        colorChooser.setColor(color);
    }
    
    public void updateDegreeLabel(){
        degreeLabel.setText(DEGREE_LABEL_TEXT+bc.getDegree());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDegreeRaisingBezier = new javax.swing.JButton();
        colorChooser = new javax.swing.JColorChooser();
        sizeLabel = new javax.swing.JLabel();
        sliderSize = new javax.swing.JSlider();
        sliderSizeLabel = new javax.swing.JLabel();
        splineLabel = new javax.swing.JLabel();
        sliderSpline = new javax.swing.JSlider();
        splitButton = new javax.swing.JButton();
        sliderSplineLabel = new javax.swing.JLabel();
        buttonDegreeRaisingCasteljau = new javax.swing.JButton();
        degreeRaisingLabel = new javax.swing.JLabel();
        degreeLabel = new javax.swing.JLabel();

        buttonDegreeRaisingBezier.setText("Bezier");
        buttonDegreeRaisingBezier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDegreeRaisingBezierActionPerformed(evt);
            }
        });

        sizeLabel.setText("Size");

        sliderSize.setMinorTickSpacing(1);
        sliderSize.setPaintLabels(true);
        sliderSize.setPaintTicks(true);
        sliderSize.setSnapToTicks(true);
        sliderSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSizeStateChanged(evt);
            }
        });

        sliderSizeLabel.setText("1");

        splineLabel.setText("t");

        sliderSpline.setMinimum(1);
        sliderSpline.setMinorTickSpacing(1);
        sliderSpline.setPaintLabels(true);
        sliderSpline.setSnapToTicks(true);
        sliderSpline.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSplineStateChanged(evt);
            }
        });

        splitButton.setText("Subdivide");
        splitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitButtonActionPerformed(evt);
            }
        });

        sliderSplineLabel.setText("1");

        buttonDegreeRaisingCasteljau.setText("Casteljau");
        buttonDegreeRaisingCasteljau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDegreeRaisingCasteljauActionPerformed(evt);
            }
        });

        degreeRaisingLabel.setText("Degree Raising");

        degreeLabel.setText("Current degree       0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(splitButton)
                        .addGap(18, 18, 18)
                        .addComponent(splineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(sliderSpline, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderSplineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderSize, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sliderSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(degreeRaisingLabel)
                                .addGap(25, 25, 25)
                                .addComponent(buttonDegreeRaisingBezier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonDegreeRaisingCasteljau))
                            .addComponent(degreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDegreeRaisingBezier, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDegreeRaisingCasteljau)
                    .addComponent(degreeRaisingLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(splineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(splitButton))
                    .addComponent(sliderSpline, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(sliderSplineLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDegreeRaisingBezierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDegreeRaisingBezierActionPerformed
        if(bc != null){
            bc.degreeRaisingBezier();
            b.recompute();
        }
    }//GEN-LAST:event_buttonDegreeRaisingBezierActionPerformed

    private void sliderSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderSizeStateChanged
        sliderSizeLabel.setText(""+sliderSize.getValue());
        b.recompute();
    }//GEN-LAST:event_sliderSizeStateChanged

    private void splitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitButtonActionPerformed
        b.subdivision((float)(sliderSpline.getValue()/100.0));
        sliderSpline.setValue(sliderSpline.getMaximum());
        sliderSizeLabel.setText(""+sliderSize.getValue());
    }//GEN-LAST:event_splitButtonActionPerformed

    private void sliderSplineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderSplineStateChanged
        if(sliderSpline.getValue()==100){
            sliderSplineLabel.setText("1");
        }else if(sliderSpline.getValue()<10){
            sliderSplineLabel.setText("0.0"+sliderSpline.getValue());
        }else{
            sliderSplineLabel.setText("0."+sliderSpline.getValue());
        }
    }//GEN-LAST:event_sliderSplineStateChanged

    private void buttonDegreeRaisingCasteljauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDegreeRaisingCasteljauActionPerformed
        if(bc != null){
            bc.degreeRaisingCasteljau();
            b.recompute();
        }
    }//GEN-LAST:event_buttonDegreeRaisingCasteljauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDegreeRaisingBezier;
    private javax.swing.JButton buttonDegreeRaisingCasteljau;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JLabel degreeRaisingLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JSlider sliderSize;
    private javax.swing.JLabel sliderSizeLabel;
    private javax.swing.JSlider sliderSpline;
    private javax.swing.JLabel sliderSplineLabel;
    private javax.swing.JLabel splineLabel;
    private javax.swing.JButton splitButton;
    // End of variables declaration//GEN-END:variables
}
